version: 2.1
orbs:
  node: circleci/node@3.0.0
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./newman/nest-api.postman_collection.json
          environment: ./newman/nest-api.postman_environment.json
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test
